let final;
let name = prompt("Hi what is your name? ");
console.log(name);
alert("welcome aboard "+ name );
let pet = prompt("What is your favourite pet? ");
console.log(pet);
alert("Oh! wow! "+ name +", I like "+pet+"s too");
let petLocation = prompt("Where do you live? ");
console.log(petLocation);
alert(name+ " a lot of people in "+petLocation + " have "+pet +"s");
let vacay = prompt("What is your next vacation destination? ");
console.log(vacay);
alert(name+", am not sure you can get on a flight to "+vacay+" from "+petLocation+" with your "+pet);